In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Ecommerce_Delivery_Analytics_New.csv")

In [3]:
df.head()

,Order ID,Customer ID,Platform,Order Date & Time,Delivery Time (Minutes),Product Category,Order Value (INR),Customer Feedback,Service Rating,Delivery Delay,Refund Requested
0,ORD000001,CUST2824,JioMart,19:29.5,30,Fruits & Vegetables,382,"Fast delivery, great service!",5,No,No
1,ORD000002,CUST1409,Blinkit,54:29.5,16,Dairy,279,Quick and reliable!,5,No,No
2,ORD000003,CUST5506,JioMart,21:29.5,25,Beverages,599,Items missing from order.,2,No,Yes
3,ORD000004,CUST5012,JioMart,19:29.5,42,Beverages,946,Items missing from order.,2,Yes,Yes
4,ORD000005,CUST4657,Blinkit,49:29.5,30,Beverages,334,"Fast delivery, great service!",5,No,No

In [5]:
df.shape

(100000, 11)

In [8]:
##Missing Values
df.isnull().sum()

Order ID                   0
Customer ID                0
Platform                   0
Order Date & Time          0
Delivery Time (Minutes)    0
Product Category           0
Order Value (INR)          0
Customer Feedback          0
Service Rating             0
Delivery Delay             0
Refund Requested           0
dtype: int64

In [9]:
##summary of the dataset
df.describe()

       Delivery Time (Minutes)  Order Value (INR)  Service Rating
count            100000.000000      100000.000000   100000.000000
mean                 29.536140         590.994400        3.240790
std                   9.958933         417.409058        1.575962
min                   5.000000          50.000000        1.000000
25%                  23.000000         283.000000        2.000000
50%                  30.000000         481.000000        3.000000
75%                  36.000000         770.000000        5.000000
max                  76.000000        2000.000000        5.000000

In [11]:
df['Order Value (INR)'].unique()

array([ 382,  279,  599, ..., 1673, 1911, 1832], shape=(1951,))

In [12]:
df['Order Value (INR)'].astype(int)

0        382
1        279
2        599
3        946
4        334
        ...
99995    289
99996    322
99997    135
99998    973
99999    453
Name: Order Value (INR), Length: 100000, dtype: int64